public inherited sharing class NodeType {
    public final static String AGGREGATE_FUNCTION = 'aggregate function';

    public final static String XFROM = 'from';
    public final static String XSELECT = 'select';
    public final static String XWHERE = 'where';
    public final static String XGROUP_BY = 'group by';
    public final static String XORDER = 'order';
    public final static String XASC = 'asc';
    public final static String XDESC = 'desc';

    public final static String XAND = 'and';
    public final static String XOR = 'or';
    public final static String XNOT = 'not';

    public final static String XTYPEOF = 'typeof';
    public final static String XEND = 'end';
    public final static String XWHEN = 'when';
    public final static String XELSE = 'else';

    public final static String CONDITONAL_SUBEXPRESSION = 'conditional subexpression';
    public final static String SUBQUERY = 'subquery';

    public final static String OPERATOR = 'operator';

    public final static String FIELD = 'field';
    public final static String SF_OBJECT = 'object';
}