/**
 * @description A class that contains the names of the Apex types.
 * @author Zackary Frazier
 * @since 11/16/2024
 */
public with sharing class ApexTypes {
    public static final String XDECIMAL = 'Decimal';
    public static final String XDOUBLE = 'Double';
    public static final String XINTEGER = 'Integer';
    public static final String XSTRING = 'String';
    public static final String XBOOLEAN = 'Boolean';
    public static final String XDATE = 'Date';
    public static final String XDATETIME = 'Datetime';
    public static final String XTIME = 'Time';
    public static final String XID = 'Id';
    public static final String XOBJECT = 'Object';
    public static final String XNULL = 'Null';
}
