public with sharing class ApexTypes {
    public static final String XDECIMAL = 'Decimal';
    public static final String XDOUBLE = 'Double';
    public static final String XINTEGER = 'Integer';
    public static final String XSTRING = 'String';
    public static final String XBOOLEAN = 'Boolean';
    public static final String XDATE = 'Date';
    public static final String XDATETIME = 'DateTime';
    public static final String XTIME = 'Time';
    public static final String XID = 'Id';
    public static final String XOBJECT = 'Object';
}